import type { MediaItem } from "./types"

export const mockMediaItems: MediaItem[] = [
  {
    id: "1",
    type: "movie",
    title: "Inception",
    description:
      "Um ladrão que rouba segredos corporativos através do uso da tecnologia de compartilhamento de sonhos recebe a tarefa inversa de plantar uma ideia na mente de um CEO.",
    imageUrl: "/inception-movie-poster.png",
    rating: 8.8,
    year: 2010,
    genres: ["Ficção Científica", "Ação", "Thriller"],
    duration: "2h 28min",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    director: "Christopher Nolan",
  },
  {
    id: "2",
    type: "series",
    title: "Breaking Bad",
    description:
      "Um professor de química do ensino médio diagnosticado com câncer de pulmão inoperável se volta para a fabricação e venda de metanfetamina para garantir o futuro de sua família.",
    imageUrl: "/breaking-bad-inspired-poster.png",
    rating: 9.5,
    year: 2008,
    genres: ["Drama", "Crime", "Thriller"],
    duration: "5 temporadas",
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
  },
  {
    id: "3",
    type: "book",
    title: "1984",
    description:
      "Uma distopia sobre um regime totalitário que usa vigilância onipresente e propaganda para controlar todos os aspectos da vida.",
    imageUrl: "/1984-book-cover.png",
    rating: 8.7,
    year: 1949,
    genres: ["Ficção Científica", "Distopia", "Clássico"],
    author: "George Orwell",
  },
  {
    id: "4",
    type: "music",
    title: "Bohemian Rhapsody",
    description:
      "Uma obra-prima do rock progressivo que combina elementos de ópera, balada e hard rock em uma única música épica.",
    imageUrl: "/queen-bohemian-rhapsody.jpg",
    rating: 9.2,
    year: 1975,
    genres: ["Rock", "Progressive Rock", "Clássico"],
    artist: "Queen",
    duration: "5:55",
  },
  {
    id: "5",
    type: "movie",
    title: "The Shawshank Redemption",
    description:
      "Dois homens presos formam um vínculo ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.",
    imageUrl: "/shawshank-redemption-poster.png",
    rating: 9.3,
    year: 1994,
    genres: ["Drama", "Crime"],
    duration: "2h 22min",
    cast: ["Tim Robbins", "Morgan Freeman"],
    director: "Frank Darabont",
  },
  {
    id: "6",
    type: "series",
    title: "Stranger Things",
    description:
      "Quando um menino desaparece, sua mãe, um chefe de polícia e seus amigos devem confrontar forças aterrorizantes para trazê-lo de volta.",
    imageUrl: "/stranger-things-inspired-poster.png",
    rating: 8.7,
    year: 2016,
    genres: ["Ficção Científica", "Horror", "Drama"],
    duration: "4 temporadas",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
  },
  {
    id: "7",
    type: "book",
    title: "Harry Potter e a Pedra Filosofal",
    description: "Um jovem bruxo descobre seu destino mágico e enfrenta o bruxo das trevas que matou seus pais.",
    imageUrl: "/generic-wizard-book-cover.png",
    rating: 8.5,
    year: 1997,
    genres: ["Fantasia", "Aventura", "Jovem Adulto"],
    author: "J.K. Rowling",
  },
  {
    id: "8",
    type: "music",
    title: "Thriller",
    description: "O álbum mais vendido de todos os tempos, definindo o som do pop dos anos 80.",
    imageUrl: "/michael-jackson-thriller.jpg",
    rating: 9.0,
    year: 1982,
    genres: ["Pop", "R&B", "Funk"],
    artist: "Michael Jackson",
  },
  {
    id: "9",
    type: "movie",
    title: "Pulp Fiction",
    description:
      "As vidas de dois assassinos da máfia, um boxeador, a esposa de um gângster e dois bandidos se entrelaçam em quatro histórias de violência e redenção.",
    imageUrl: "/generic-movie-poster.png",
    rating: 8.9,
    year: 1994,
    genres: ["Crime", "Drama"],
    duration: "2h 34min",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    director: "Quentin Tarantino",
  },
  {
    id: "10",
    type: "series",
    title: "The Crown",
    description:
      "Segue a vida política da Rainha Elizabeth II e os eventos que moldaram a segunda metade do século 20.",
    imageUrl: "/the-crown-poster.jpg",
    rating: 8.6,
    year: 2016,
    genres: ["Drama", "História", "Biografia"],
    duration: "6 temporadas",
    cast: ["Claire Foy", "Olivia Colman", "Imelda Staunton"],
  },
  {
    id: "11",
    type: "book",
    title: "O Senhor dos Anéis",
    description:
      "Uma jornada épica através da Terra-média para destruir um anel de poder antes que caia nas mãos erradas.",
    imageUrl: "/lord-of-the-rings-book.jpg",
    rating: 9.0,
    year: 1954,
    genres: ["Fantasia", "Aventura", "Épico"],
    author: "J.R.R. Tolkien",
  },
  {
    id: "12",
    type: "music",
    title: "Dark Side of the Moon",
    description: "Um álbum conceitual que explora temas de conflito, ganância, tempo e doença mental.",
    imageUrl: "/pink-floyd-dark-side.jpg",
    rating: 9.1,
    year: 1973,
    genres: ["Rock Progressivo", "Psicodélico", "Art Rock"],
    artist: "Pink Floyd",
  },
  {
    id: "13",
    type: "movie",
    title: "Interstellar",
    description:
      "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço em uma tentativa de garantir a sobrevivência da humanidade.",
    imageUrl: "/interstellar-inspired-poster.png",
    rating: 8.6,
    year: 2014,
    genres: ["Ficção Científica", "Drama", "Aventura"],
    duration: "2h 49min",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    director: "Christopher Nolan",
  },
  {
    id: "14",
    type: "series",
    title: "Game of Thrones",
    description:
      "Nove famílias nobres lutam pelo controle das terras míticas de Westeros, enquanto um antigo inimigo retorna.",
    imageUrl: "/game-of-thrones-inspired-poster.png",
    rating: 9.2,
    year: 2011,
    genres: ["Fantasia", "Drama", "Aventura"],
    duration: "8 temporadas",
    cast: ["Emilia Clarke", "Kit Harington", "Peter Dinklage"],
  },
  {
    id: "15",
    type: "book",
    title: "Cem Anos de Solidão",
    description:
      "A história multi-geracional da família Buendía, cujo patriarca, José Arcadio Buendía, fundou a cidade fictícia de Macondo.",
    imageUrl: "/cem-anos-de-solidao-book.jpg",
    rating: 8.8,
    year: 1967,
    genres: ["Realismo Mágico", "Ficção Literária", "Clássico"],
    author: "Gabriel García Márquez",
  },
  {
    id: "16",
    type: "music",
    title: "Abbey Road",
    description: "O penúltimo álbum dos Beatles, conhecido por sua icônica capa e medley no lado B.",
    imageUrl: "/beatles-abbey-road.jpg",
    rating: 8.9,
    year: 1969,
    genres: ["Rock", "Pop Rock", "Clássico"],
    artist: "The Beatles",
  },
  {
    id: "17",
    type: "movie",
    title: "Parasita",
    description:
      "Ganância e discriminação de classe ameaçam a relação simbiótica recém-formada entre a família rica Park e o clã indigente Kim.",
    imageUrl: "/parasite-movie-poster.png",
    rating: 8.6,
    year: 2019,
    genres: ["Thriller", "Drama", "Comédia Negra"],
    duration: "2h 12min",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    director: "Bong Joon-ho",
  },
  {
    id: "18",
    type: "series",
    title: "The Office",
    description:
      "Um olhar mockumentary sobre o dia a dia dos funcionários de escritório na Dunder Mifflin Paper Company.",
    imageUrl: "/the-office-poster.jpg",
    rating: 9.0,
    year: 2005,
    genres: ["Comédia", "Mockumentary"],
    duration: "9 temporadas",
    cast: ["Steve Carell", "Rainn Wilson", "John Krasinski"],
  },
  {
    id: "19",
    type: "book",
    title: "O Grande Gatsby",
    description: "Uma crítica à decadência e ao excesso da Era do Jazz, contada através dos olhos de Nick Carraway.",
    imageUrl: "/great-gatsby-book.png",
    rating: 8.3,
    year: 1925,
    genres: ["Ficção Literária", "Clássico", "Romance"],
    author: "F. Scott Fitzgerald",
  },
  {
    id: "20",
    type: "music",
    title: "Nevermind",
    description: "O álbum que trouxe o grunge para o mainstream e definiu uma geração.",
    imageUrl: "/nirvana-nevermind.jpg",
    rating: 8.7,
    year: 1991,
    genres: ["Grunge", "Rock Alternativo"],
    artist: "Nirvana",
  },
]
